#!/bin/bash
# START HERE - Quick VS Code Authentication Fix
# Run this script on your Jetson Orin at 192.168.1.145

clear
echo "════════════════════════════════════════════════════════════════"
echo "  VS Code Authentication Fix - Jetson Orin @ 192.168.1.145"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Problem: VS Code freezes at http://127.0.0.1:63061 during sign-in"
echo ""
echo "✅ SOLUTION: Use Device Code Authentication"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "STEP 1: Open VS Code on your Jetson"
echo "─────────────────────────────────────"
echo "   cd /home/curtis/avatar-pipeline"
echo "   code ."
echo ""
echo "STEP 2: Open Command Palette in VS Code"
echo "─────────────────────────────────────"
echo "   Press: Ctrl+Shift+P"
echo ""
echo "STEP 3: Select Device Code Authentication"
echo "─────────────────────────────────────"
echo "   Type: GitHub Copilot: Sign in Using Device Code"
echo "   Press: Enter"
echo ""
echo "STEP 4: VS Code will show you a code"
echo "─────────────────────────────────────"
echo "   Example: ABCD-1234"
echo ""
echo "STEP 5: Authorize on GitHub"
echo "─────────────────────────────────────"
echo "   • Click the link VS Code provides, OR"
echo "   • Open browser and go to: https://github.com/login/device"
echo "   • Enter your device code"
echo "   • Click 'Authorize'"
echo ""
echo "STEP 6: Done! Return to VS Code"
echo "─────────────────────────────────────"
echo "   You should now be signed in ✅"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📚 Documentation:"
echo "   • Quick Fix Guide: VSCODE_QUICK_FIX.md"
echo "   • Full Guide: VSCODE_SETUP.md"
echo "   • Automated Fixes: ./fix_vscode_auth.sh"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
read -p "Would you like to run the automated fix script? (y/n) " -n 1 -r
echo ""

if [[ $REPLY =~ ^[Yy]$ ]]; then
    ./fix_vscode_auth.sh
else
    echo ""
    echo "No problem! Follow the steps above manually."
    echo ""
    echo "If you need help, run: ./fix_vscode_auth.sh"
    echo ""
fi
